### ISSUE TITLE
Access token publically shown

### ISSUE THREAD

**Issue by wasurocks** [Maoragai12/nx-aws-sam#11]
Hi there,

First off, thanks for sharing this repository. After cloning your repo, I noticed that when running scripts Nx cloud works off the bat. I got confused as to why this was working (I could run on Nx cloud without having ever created an account) and then I noticed you had left your access token in the `nx.json` file. You might want to hide it from there in case someone finds it. Good luck!

**Comment by Maoragai12** [comment]
> Hi there,
> 
> 
> 
> First off, thanks for sharing this repository. After cloning your repo, I noticed that when running scripts Nx cloud works off the bat. I got confused as to why this was working (I could run on Nx cloud without having ever created an account) and then I noticed you had left your access token in the `nx.json` file. You might want to hide it from there in case someone finds it. Good luck!

Hi man, how are you?

I'm happy that you liked this repo, I worked on that really hard. 

Thank you for letting me know about the token, I took care of that. 

Thanks!
